### ISSUE TITLE
infiniteRasa story

### ISSUE THREAD

**Issue by damuras** [InfiniteRasa/Game-Server#11]
So what happen with the IR community and what is holding this project from coming back to life? What are the legal terms and conditions that NCSoft said? Any and all details would be nice to share.

**Comment by Darkblade** [comment]
not sure at the moment, I just know the domain is offline.

**Comment by edolnx** [comment]
Domain should be fixed at this point, we had a problem with one of our providers. I disabled them.

**Comment by damuras** [comment]
well infiniterasa.com is owned by ncsoft, but not infiniterasa.org

**Comment by damuras** [comment]
Done
