### ISSUE TITLE
where is the game client?

### ISSUE THREAD

**Issue by Elegent** [InfiniteRasa/Game-Server#12]
where is the game client?

hi ,all.

i try my best, but I can't find the game-client,where is it?

**Comment by edolnx** [comment]
Available via BitTorrent using the DHT hash:

F6165F0146327B4398BE5193E2F005CB12B73020

**Comment by Elegent** [comment]
Thank you,

taday i used your DHT hash code in BitTorrent Sync 1.2.67

I  can only get an error,

"The secret is invalid please regenerate" 

 is it out of date?

can you  provide a  new one?

**Comment by Elegent** [comment]
em,use your code i get this,

the game-client:TabulaRasa1.16.5.0.rar ,

i mean, 

i really need some  game-cilent test code,

**Comment by Elegent** [comment]
i try to write it !!

**Comment by damuras** [comment]
To by a legal copy
http://www.ebay.com/sch/Video-Games-/139973/i.html?_from=R40&_nkw=tabula+rasa

OR 

Download the demo
http://www.fileplanet.com/195728/download/Tabula-Rasa-Full-Game-Client-%28Free-MMO%29

**Comment by edolnx** [comment]
Note: the version of TR shipped in packaging is very old and will not work with the IR GameServer. The demo may or may not work, I don't know what version is shipped. The best method is still this torrent:

magnet:?xt=urn:btih:f6165f0146327b4398be5193e2f005cb12b73020

As you said before, that just provides a RAR file with the client.
