### ISSUE TITLE
Duplicate files due to merge

### ISSUE THREAD

**Issue by gentili** [InfiniteRasa/Game-Server#24]
The merge from the damuras branch didn't remove the old files from the root.

I'm going to clean that up and submit a pull request, unless someone else is already on it.  (speak now if you are :)

**Comment by damuras** [comment]
A clean up would be nice indeed!

**Comment by Dahrkael** [comment]
go ahead, also damuras. As you pushed everything in a row, I cant see the changes to the actual code (not libs). whats new?

**Comment by damuras** [comment]
Well you can find patch notes below at the link. All work and reorganization of the code was performed by Knightsoulder. 

http://infiniterasa.org/viewforum.php?f=19

**Comment by gentili** [comment]
Dahrkael, the problem is that the code that was changed has actually been moved to a new directory, but the old files were left in root by the merge.  I'll put together a changeset that does the move, and applies the commits so we can see the work Knightsoulder and company have done.

**Comment by gentili** [comment]
Pull request is ready.  Any way I can be part of the InfiniteRasa org?  I've got a bunch more cleanup and documentation I'd like to do.

**Comment by krssrb** [comment]
damuras it's not latest work of Knightsoulder, there was 1 or 2 commit's from him after this one u posted, i can give u link if u want

**Comment by gentili** [comment]
Those commits aren't in the svn repo damuras pointed me to?

**Comment by krssrb** [comment]
no, check this https://github.com/krssrb/Game_Server/tree/dev

**Comment by gentili** [comment]
You mind if I merge that into my branch forked from the InfiniteRasa repo?
It would be good if we started working off the same root repo to avoid all this weird cross repo/scm merge complexity.

**Comment by krssrb** [comment]
go ahead, that's why i uploaded it, so we continue work togeder with latest work

**Comment by gentili** [comment]
cool I'm on it...

**Comment by Dahrkael** [comment]
so, do I merge the pull request or not. I'll add you to the repo anyway, so go ahead and commit as you want

**Comment by gentili** [comment]
Go ahead and merge it and I'll add krssrb's commits after.

**Comment by gentili** [comment]
Merged and cleaned
