### ISSUE TITLE
Web page down?

### ISSUE THREAD

**Issue by krssrb** [InfiniteRasa/Game-Server#27]
IDK where else to put this msg, but Web page isn't working since 01/01/2016.
Why?

**Comment by Dahrkael** [comment]
Probably due to low activity damuras decided not to renew the domain/hosting?
i dont really know, but to avoid another forum going down we could just use this issue tracker for help and the wiki for information. just an idea

**Comment by damuras** [comment]
Sorry its my fault! Im trying to cut some personal expenses and closed one of my vps iv been renting and move stuff to just one. Unfortunately, it seems i forgot to move the db dump and cannot get it back. Im sorry guys! I am working on a new site to post up soon. And I promise not to screw up the site again!

**Comment by krssrb** [comment]
1 question? Should we share our work ( well not our work, but redirect them here) on some other site's? Like Ragezone or something like that, they have  develpoers for many mmorpg's, maybe someone is interested in Tabula rasa?
