### ISSUE TITLE
Client error message while activating Sprint...

### ISSUE THREAD

**Issue by sheng-gradilla** [InfiniteRasa/Game-Server#5]
I cloned everything from the repository today.
# Whenever I activate Sprint, the client gives me this error:

Python Exception:
File: python/client\gameeffects\basegameeffect.py
Line: 159
# TypeError: OnAttach() takes exactly 3 arguments (2 given)

I am using the client as it was the day TR closed. My trpython.zip file has date of Feb 17 2009. Is everyone getting this same error?

**Comment by kthxbye** [comment]
Ooops, my fault. I forgot to fix gameEffect_attachSprint() after I tried out some stuff. I just pushed a small commit which should make the sprint effect working again.

**Comment by sheng-gradilla** [comment]
it works now :)
