### ISSUE TITLE
How do you bypass the playNC launcher?

### ISSUE THREAD

**Issue by damuras** [InfiniteRasa/Game-Server#6]

**Comment by Dahrkael** [comment]
the launcher just passes some arguments to the games exe, so we pass them by hand.

**Comment by damuras** [comment]
So once the game server gets compiled it will work? I got the auth server working. If i can get this going maybe i can draw in others to help. I know NC shut the emu down but still...

**Comment by kthxbye** [comment]
The best way is to create a shortcut to the TabulaRasa.exe and add the following command line parameters: /NoPatch /AuthServer=localhost:2106
This will skip the launcher and tell the client to connect to the local machine.

**Comment by damuras** [comment]
will do, im using the master code atm

**Comment by damuras** [comment]
Got game to launch
