### ISSUE TITLE
TabulaGameServer.exe

### ISSUE THREAD

**Issue by damuras** [InfiniteRasa/Game-Server#7]
Compiled from master branch. When executing the gameserver i get a system error. LIBMYSQL.dll is missing. Is that not included in the build process or do i need to download this and put it in the debug directory when launching the gameserver?

Thanks for your assistance.

**Comment by damuras** [comment]
Ok got that working now! Now server is just crashing as soon as i launch it. I do have the auth server running.

**Comment by kthxbye** [comment]
Have you setup the mysql database and imported gameDB.sql? You also need to update the config.ini file.

If you are using Visual Studio go into Project Settings -> Configuration Properties -> Debugging and set the Working Directory to "$(SolutionDir)\bin\" (without the ") This is required for the server to find the gameData directory.

**Comment by kthxbye** [comment]
Update: I just committed a small patch that removes the need to set the correct working directory (experimental branch). So all you need to do is to setup the mysql database and config.ini file.

**Comment by damuras** [comment]
lol lazy devs... well im not really much of a dev yet but im studying computer science. Thanks for the help =D

**Comment by Dahrkael** [comment]
use the experimental branch, the master branch is more like a memorial repository lol

**Comment by damuras** [comment]
gonna work on a bat file to do all the db installs for future users. I will post if i have any other questions.
