### ISSUE TITLE
Experimental Issues

### ISSUE THREAD

**Issue by damuras** [InfiniteRasa/Game-Server#8]
Ok yes maybe I am missing a simple step... 

I am using VS 2012 express for desktop

just downloading and building the source as it, with no changes i get 6 errors all.

Looks like i am missing /recastnavigation folder so can i just make the folder, and move the files it is looking for into the folder?

Error   1   error C1083: Cannot open source file: '3rdparty\recastnavigation\DetourNode.cpp': No such file or directory C:\Users***\Documents\***\TR\Game-Server-experimental\c1xx TabulaGameServer

Error   2   error C1083: Cannot open source file: '3rdparty\recastnavigation\DetourNavMeshQuery.cpp': No such file or directory C:\Users***\Documents\***\TR\Game-Server-experimental\c1xx TabulaGameServer

Error   3   error C1083: Cannot open source file: '3rdparty\recastnavigation\DetourNavMeshBuilder.cpp': No such file or directory   C:\Users***\Documents\***\TR\Game-Server-experimental\c1xx TabulaGameServer

Error   4   error C1083: Cannot open source file: '3rdparty\recastnavigation\DetourNavMesh.cpp': No such file or directory  C:\Users***\Documents\***\TR\Game-Server-experimental\c1xx TabulaGameServer

Error   5   error C1083: Cannot open source file: '3rdparty\recastnavigation\DetourCommon.cpp': No such file or directory   C:\Users***\Documents\***\TR\Game-Server-experimental\c1xx TabulaGameServer

Error   6   error C1083: Cannot open source file: '3rdparty\recastnavigation\DetourAlloc.cpp': No such file or directory    C:\Users***\Documents\***\TR\Game-Server-experimental\c1xx TabulaGameServer

**Comment by damuras** [comment]
Ok so i have the files moved and pointed to in the code and the errors are now gone. One last error im having issues with and cannot seem to get past is:
LINK : fatal error LNK1104: cannot open file 'libmysql.lib'
when i move or copy this file to the working directory i get a lot more errors, i have also tried using the full path to the lib, maybe im missing something else. Any ideas would be hot, thanks.

**Comment by kthxbye** [comment]
Are you still stuck with the errors? I remember the Express editions of VS do not support subdirectories for cpp/header files or libs. To solve this, you need to copy all .cpp .h and .lib files inside the 3rdparty directory into the main project directory, you may also need to adjust all the changed paths in the #include directives. If you still get errors, it would be helpful if you post them here.

**Comment by damuras** [comment]
Ok i will give that a shot tomorrow, thanks. will let ya know how it goes.

**Comment by damuras** [comment]
Error   252 error LNK1104: cannot open file 'libmysql.lib'  C:\Users***_\Documents\**_*\TR\Game-Server-experimental\LINK   TabulaGameServer

If i move that file into the main directory it still fails. Now i didnt move any files into the main directory but the libmysql.lib and libmysql.dll as they were the only two that were included in the build of the project. all other files in the 3rd party directories were flagged "excluded"

Error   2   error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in DataInterface_Teleporter.obj C:\Users***_\Documents\**__\TR\Game-Server-experimental\GameMain.obj   TabulaGameServer
Error   3   error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in DataInterface_Teleporter.obj C:\Users\_**_\Documents\**__\TR\Game-Server-experimental\MapChannel.obj TabulaGameServer
Error   4   error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in DataInterface_Teleporter.obj C:\Users\_**_\Documents\**__\TR\Game-Server-experimental\CharacterMgr.obj   TabulaGameServer
Error   5   error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in DataInterface_Teleporter.obj C:\Users\_**_\Documents\**__\TR\Game-Server-experimental\netMgr.obj TabulaGameServer
Error   6   error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in DataInterface_Teleporter.obj C:\Users\_**_\Documents\**__\TR\Game-Server-experimental\PyMarshal.obj  TabulaGameServer
Error   7   error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in DataInterface_Teleporter.obj C:\Users\_**_\Documents\**__\TR\Game-Server-experimental\teleporter.obj TabulaGameServer
Error   8   error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in DataInterface_Teleporter.obj C:\Users\_**_\Documents\**__\TR\Game-Server-experimental\gameData.obj   TabulaGameServer
Error   9   error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in DataInterface_Teleporter.obj C:\Users\_**_\Documents\**__\TR\Game-Server-experimental\entityMgr.obj  TabulaGameServer
Error   10  error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in DataInterface_Teleporter.obj C:\Users\_**_\Documents\**__\TR\Game-Server-experimental\manifestation.obj  TabulaGameServer
Error   11  error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in DataInterface_Teleporter.obj C:\Users\_**_\Documents\**__\TR\Game-Server-experimental\playerActions.obj  TabulaGameServer
Error   12  error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in DataInterface_Teleporter.obj C:\Users\_**_\Documents\**__\TR\Game-Server-experimental\communicator.obj   TabulaGameServer
Error   13  error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in DataInterface_Teleporter.obj C:\Users\_**_\Documents\**__\TR\Game-Server-experimental\inventory.obj  TabulaGameServer
Error   14  error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in DataInterface_Teleporter.obj C:\Users\_**_\Documents\**__\TR\Game-Server-experimental\dynamicObject.obj  TabulaGameServer
Error   15  error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in DataInterface_Teleporter.obj C:\Users\_**_\Documents\**__\TR\Game-Server-experimental\cellMgr.obj    TabulaGameServer
Error   16  error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in DataInterface_Teleporter.obj C:\Users\_**_\Documents\**__\TR\Game-Server-experimental\npc.obj    TabulaGameServer
Error   17  error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in DataInterface_Teleporter.obj C:\Users\_**_\Documents\**__\TR\Game-Server-experimental\gameEffects.obj    TabulaGameServer
Error   18  error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in DataInterface_Teleporter.obj C:\Users\_**_\Documents\**__\TR\Game-Server-experimental\mission.obj    TabulaGameServer
Error   19  error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in DataInterface_Teleporter.obj C:\Users\_**_\Documents\**__\TR\Game-Server-experimental\creature.obj   TabulaGameServer
Error   20  error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in DataInterface_Teleporter.obj C:\Users\_**_\Documents\**__\TR\Game-Server-experimental\spawnSystem.obj    TabulaGameServer
Error   21  error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in DataInterface_Teleporter.obj C:\Users\_**_\Documents\**__\TR\Game-Server-experimental\missile.obj    TabulaGameServer
Error   22  error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in DataInterface_Teleporter.obj C:\Users\_**_\Documents\**__\TR\Game-Server-experimental\behaviorController.obj TabulaGameServer
Error   23  error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in DataInterface_Teleporter.obj C:\Users\_**_\Documents\**__\TR\Game-Server-experimental\main.obj   TabulaGameServer
Error   24  error LNK2019: unresolved external symbol "void __cdecl Thread::InitMutex(struct _RTL_CRITICAL_SECTION *)" (?InitMutex@Thread@@YAXPAU_RTL_CRITICAL_SECTION@@@Z) referenced in function "void __cdecl _mission_addNPCMissionRelation(struct _npc_t *,int)" (?_mission_addNPCMissionRelation@@YAXPAU_npc_t@@H@Z)  C:\Users\_**_\Documents\**__\TR\Game-Server-experimental\mission.obj    TabulaGameServer
Error   25  error LNK2001: unresolved external symbol "void __cdecl Thread::InitMutex(struct _RTL_CRITICAL_SECTION *)" (?InitMutex@Thread@@YAXPAU_RTL_CRITICAL_SECTION@@@Z) C:\Users\_**_\Documents\**__\TR\Game-Server-experimental\GameMain.obj   TabulaGameServer
Error   26  error LNK2001: unresolved external symbol "void __cdecl Thread::InitMutex(struct _RTL_CRITICAL_SECTION *)" (?InitMutex@Thread@@YAXPAU_RTL_CRITICAL_SECTION@@@Z) C:\Users\_**_\Documents\**__\TR\Game-Server-experimental\MapChannel.obj TabulaGameServer
Error   27  error LNK2001: unresolved external symbol "void __cdecl Thread::InitMutex(struct _RTL_CRITICAL_SECTION *)" (?InitMutex@Thread@@YAXPAU_RTL_CRITICAL_SECTION@@@Z) C:\Users\_**_\Documents\**__\TR\Game-Server-experimental\entityMgr.obj  TabulaGameServer
Error   28  error LNK2001: unresolved external symbol "void __cdecl Thread::InitMutex(struct _RTL_CRITICAL_SECTION *)" (?InitMutex@Thread@@YAXPAU_RTL_CRITICAL_SECTION@@@Z) C:\Users\_**_\Documents\**__\TR\Game-Server-experimental\communicator.obj   TabulaGameServer
Error   29  error LNK2001: unresolved external symbol "void __cdecl Thread::LockMutex(struct _RTL_CRITICAL_SECTION *)" (?LockMutex@Thread@@YAXPAU_RTL_CRITICAL_SECTION@@@Z) C:\Users\_**_\Documents\**__\TR\Game-Server-experimental\communicator.obj   TabulaGameServer
Error   30  error LNK2019: unresolved external symbol "void __cdecl Thread::LockMutex(struct _RTL_CRITICAL_SECTION *)" (?LockMutex@Thread@@YAXPAU_RTL_CRITICAL_SECTION@@@Z) referenced in function "struct _clientGamemain_t \* __cdecl ClientMgr_AddToGameMain(unsigned int)" (?ClientMgr_AddToGameMain@@YAPAU_clientGamemain_t@@I@Z)   C:\Users\_**_\Documents\**__\TR\Game-Server-experimental\GameMain.obj   TabulaGameServer
Error   31  error LNK2001: unresolved external symbol "void __cdecl Thread::LockMutex(struct _RTL_CRITICAL_SECTION *)" (?LockMutex@Thread@@YAXPAU_RTL_CRITICAL_SECTION@@@Z) C:\Users\_**_\Documents\**__\TR\Game-Server-experimental\MapChannel.obj TabulaGameServer
Error   32  error LNK2001: unresolved external symbol "void __cdecl Thread::LockMutex(struct _RTL_CRITICAL_SECTION *)" (?LockMutex@Thread@@YAXPAU_RTL_CRITICAL_SECTION@@@Z) C:\Users\_**_\Documents\**__\TR\Game-Server-experimental\netMgr.obj TabulaGameServer
Error   33  error LNK2001: unresolved external symbol "void __cdecl Thread::LockMutex(struct _RTL_CRITICAL_SECTION *)" (?LockMutex@Thread@@YAXPAU_RTL_CRITICAL_SECTION@@@Z) C:\Users\_**_\Documents\**__\TR\Game-Server-experimental\entityMgr.obj  TabulaGameServer
Error   34  error LNK2001: unresolved external symbol "void __cdecl Thread::UnlockMutex(struct _RTL_CRITICAL_SECTION *)" (?UnlockMutex@Thread@@YAXPAU_RTL_CRITICAL_SECTION@@@Z) C:\Users\_**_\Documents\**__\TR\Game-Server-experimental\communicator.obj   TabulaGameServer
Error   35  error LNK2019: unresolved external symbol "void __cdecl Thread::UnlockMutex(struct _RTL_CRITICAL_SECTION *)" (?UnlockMutex@Thread@@YAXPAU_RTL_CRITICAL_SECTION@@@Z) referenced in function "struct _clientGamemain_t \* __cdecl ClientMgr_AddToGameMain(unsigned int)" (?ClientMgr_AddToGameMain@@YAPAU_clientGamemain_t@@I@Z)   C:\Users\_**_\Documents\**__\TR\Game-Server-experimental\GameMain.obj   TabulaGameServer
Error   36  error LNK2001: unresolved external symbol "void __cdecl Thread::UnlockMutex(struct _RTL_CRITICAL_SECTION *)" (?UnlockMutex@Thread@@YAXPAU_RTL_CRITICAL_SECTION@@@Z) C:\Users\_**_\Documents\**__\TR\Game-Server-experimental\MapChannel.obj TabulaGameServer
Error   37  error LNK2001: unresolved external symbol "void __cdecl Thread::UnlockMutex(struct _RTL_CRITICAL_SECTION *)" (?UnlockMutex@Thread@@YAXPAU_RTL_CRITICAL_SECTION@@@Z) C:\Users\_**_\Documents\**__\TR\Game-Server-experimental\netMgr.obj TabulaGameServer
Error   38  error LNK2001: unresolved external symbol "void __cdecl Thread::UnlockMutex(struct _RTL_CRITICAL_SECTION *)" (?UnlockMutex@Thread@@YAXPAU_RTL_CRITICAL_SECTION@@@Z) C:\Users\_**_\Documents\**__\TR\Game-Server-experimental\entityMgr.obj  TabulaGameServer
Error   39  error LNK2019: unresolved external symbol "bool __cdecl Thread::New(unsigned long *,unsigned long (__stdcall_)(void _),void *)" (?New@Thread@@YA_NPAKP6GKPAX@Z1@Z) referenced in function "void __cdecl mapChannel_start(int *,int)" (?mapChannel_start@@YAXPAHH@Z) C:\Users\_**_\Documents\**__\TR\Game-Server-experimental\MapChannel.obj TabulaGameServer
Error   40  error LNK2001: unresolved external symbol "bool __cdecl Thread::New(unsigned long *,unsigned long (__stdcall_)(void _),void *)" (?New@Thread@@YA_NPAKP6GKPAX@Z1@Z)  C:\Users\_**_\Documents\**__\TR\Game-Server-experimental\main.obj   TabulaGameServer
Error   41  error LNK2001: unresolved external symbol "bool __cdecl Thread::New(unsigned long *,unsigned long (__stdcall_)(void _),void *)" (?New@Thread@@YA_NPAKP6GKPAX@Z1@Z)  C:\Users\_**_\Documents\**__\TR\Game-Server-experimental\DataInterface.obj  TabulaGameServer
Error   42  error LNK2001: unresolved external symbol "void __cdecl hashTable_init(struct hashTable_t *,int)" (?hashTable_init@@YAXPAUhashTable_t@@H@Z) C:\Users\_**_\Documents\**__\TR\Game-Server-experimental\cellMgr.obj    TabulaGameServer
Error   43  error LNK2001: unresolved external symbol "void __cdecl hashTable_init(struct hashTable_t *,int)" (?hashTable_init@@YAXPAUhashTable_t@@H@Z) C:\Users\_**_\Documents\**__\TR\Game-Server-experimental\mission.obj    TabulaGameServer
Error   44  error LNK2019: unresolved external symbol "void __cdecl hashTable_init(struct hashTable_t *,int)" (?hashTable_init@@YAXPAUhashTable_t@@H@Z) referenced in function "void __cdecl mapChannel_init(void)" (?mapChannel_init@@YAXXZ)   C:\Users\_**_\Documents\**__\TR\Game-Server-experimental\MapChannel.obj TabulaGameServer
Error   45  error LNK2001: unresolved external symbol "void __cdecl hashTable_init(struct hashTable_t *,int)" (?hashTable_init@@YAXPAUhashTable_t@@H@Z) C:\Users\_**_\Documents\**__\TR\Game-Server-experimental\gameData.obj   TabulaGameServer 
Error   46  error LNK2001: unresolved external symbol "void __cdecl hashTable_init(struct hashTable_t *,int)" (?hashTable_init@@YAXPAUhashTable_t@@H@Z) C:\Users\_**_\Documents\**__\TR\Game-Server-experimental\entityMgr.obj  TabulaGameServer
Error   47  error LNK2001: unresolved external symbol "void __cdecl hashTable_init(struct hashTable_t *,int)" (?hashTable_init@@YAXPAUhashTable_t@@H@Z) C:\Users\_**_\Documents\**__\TR\Game-Server-experimental\communicator.obj   TabulaGameServer
Error   48  error LNK2001: unresolved external symbol "bool __cdecl hashTable_set(struct hashTable_t *,unsigned int,void *)" (?hashTable_set@@YA_NPAUhashTable_t@@IPAX@Z)   C:\Users\_**_\Documents\**__\TR\Game-Server-experimental\cellMgr.obj    TabulaGameServer
Error   49  error LNK2019: unresolved external symbol "bool __cdecl hashTable_set(struct hashTable_t *,unsigned int,void *)" (?hashTable_set@@YA_NPAUhashTable_t@@IPAX@Z) referenced in function "void __cdecl _cb_mapChannel_addNewPlayer(void *,struct diJob_characterData_t *)" (?_cb_mapChannel_addNewPlayer@@YAXPAXPAUdiJob_characterData_t@@@Z)   C:\Users\_**_\Documents\**__\TR\Game-Server-experimental\MapChannel.obj TabulaGameServer
Error   50  error LNK2001: unresolved external symbol "bool __cdecl hashTable_set(struct hashTable_t *,unsigned int,void *)" (?hashTable_set@@YA_NPAUhashTable_t@@IPAX@Z)   C:\Users\_**_\Documents\**__\TR\Game-Server-experimental\gameData.obj   TabulaGameServer
Error   51  error LNK2001: unresolved external symbol "bool __cdecl hashTable_set(struct hashTable_t *,unsigned int,void *)" (?hashTable_set@@YA_NPAUhashTable_t@@IPAX@Z)   C:\Users\_**_\Documents\**__\TR\Game-Server-experimental\entityMgr.obj  TabulaGameServer
Error   52  error LNK2001: unresolved external symbol "bool __cdecl hashTable_set(struct hashTable_t *,unsigned int,void *)" (?hashTable_set@@YA_NPAUhashTable_t@@IPAX@Z)   C:\Users\_**_\Documents\**__\TR\Game-Server-experimental\communicator.obj   TabulaGameServer
Error   53  error LNK2001: unresolved external symbol "void \* __cdecl hashTable_get(struct hashTable_t *,unsigned int)" (?hashTable_get@@YAPAXPAUhashTable_t@@I@Z)  C:\Users\_**_\Documents\**__\TR\Game-Server-experimental\cellMgr.obj    TabulaGameServer
Error   54  error LNK2019: unresolved external symbol "void \* __cdecl hashTable_get(struct hashTable_t *,unsigned int)" (?hashTable_get@@YAPAXPAUhashTable_t@@I@Z) referenced in function "struct _mapChannel_t \* __cdecl mapChannel_findByContextId(int)" (?mapChannel_findByContextId@@YAPAU_mapChannel_t@@H@Z)   C:\Users\_**_\Documents\**__\TR\Game-Server-experimental\MapChannel.obj TabulaGameServer
Error   55  error LNK2001: unresolved external symbol "void \* __cdecl hashTable_get(struct hashTable_t *,unsigned int)" (?hashTable_get@@YAPAXPAUhashTable_t@@I@Z)  C:\Users\_**_\Documents\**__\TR\Game-Server-experimental\gameData.obj   TabulaGameServer
Error   56  error LNK2001: unresolved external symbol "void \* __cdecl hashTable_get(struct hashTable_t *,unsigned int)" (?hashTable_get@@YAPAXPAUhashTable_t@@I@Z)  C:\Users\_**_\Documents\**__\TR\Game-Server-experimental\entityMgr.obj  TabulaGameServer
Error   57  error LNK2001: unresolved external symbol "void \* __cdecl hashTable_get(struct hashTable_t *,unsigned int)" (?hashTable_get@@YAPAXPAUhashTable_t@@I@Z)  C:\Users\_**_\Documents\**__\TR\Game-Server-experimental\communicator.obj   TabulaGameServer
Error   58  error LNK2019: unresolved external symbol "void __cdecl navmesh_initForMapChannel(struct _mapChannel_t *)" (?navmesh_initForMapChannel@@YAXPAU_mapChannel_t@@@Z) referenced in function "int __cdecl mapChannel_worker(struct mapChannelList_t *)" (?mapChannel_worker@@YAHPAUmapChannelList_t@@@Z) C:\Users\_**_\Documents\**__\TR\Game-Server-experimental\MapChannel.obj TabulaGameServer
Error   59  error LNK2019: unresolved external symbol "void __cdecl waypoint_recv_SelectWaypoint(struct _mapChannelClient_t *,unsigned char *,int)" (?waypoint_recv_SelectWaypoint@@YAXPAU_mapChannelClient_t@@PAEH@Z) referenced in function "void __cdecl mapChannel_processPythonRPC(struct _mapChannelClient_t *,unsigned int,unsigned char *,int)" (?mapChannel_processPythonRPC@@YAXPAU_mapChannelClient_t@@IPAEH@Z)  C:\Users\_**_\Documents\**__\TR\Game-Server-experimental\MapChannel.obj TabulaGameServer
Error   60  error LNK2019: unresolved external symbol "struct _dynObject_t \* __cdecl waypoint_create(struct _mapChannel_t *,float,float,float,float,unsigned int,unsigned int)" (?waypoint_create@@YAPAU_dynObject_t@@PAU_mapChannel_t@@MMMMII@Z) referenced in function "void __cdecl _cb_teleporter_initForMapChannel(void *,struct diJob_teleporterData *)" (?_cb_teleporter_initForMapChannel@@YAXPAXPAUdiJob_teleporterData@@@Z)   C:\Users\_**_\Documents\**__\TR\Game-Server-experimental\teleporter.obj TabulaGameServer
Error   61  error LNK2019: unresolved external symbol "bool __cdecl hashTable_set(struct hashTable_t *,char *,void *)" (?hashTable_set@@YA_NPAUhashTable_t@@PADPAX@Z) referenced in function "void __cdecl _gameData_loadItemTemplates(void)" (?_gameData_loadItemTemplates@@YAXXZ) C:\Users\_**_\Documents\**__\TR\Game-Server-experimental\gameData.obj   TabulaGameServer
Error   62  error LNK2001: unresolved external symbol "bool __cdecl hashTable_set(struct hashTable_t *,char *,void *)" (?hashTable_set@@YA_NPAUhashTable_t@@PADPAX@Z)   C:\Users\_**_\Documents\**__\TR\Game-Server-experimental\communicator.obj   TabulaGameServer
Error   63  error LNK2019: unresolved external symbol "void \* __cdecl hashTable_get(struct hashTable_t *,char *)" (?hashTable_get@@YAPAXPAUhashTable_t@@PAD@Z) referenced in function "struct itemTemplate_t \* __cdecl gameData_getItemTemplateByName(char *)" (?gameData_getItemTemplateByName@@YAPAUitemTemplate_t@@PAD@Z)    C:\Users\_**_\Documents\**__\TR\Game-Server-experimental\gameData.obj   TabulaGameServer
Error   64  error LNK2001: unresolved external symbol "void \* __cdecl hashTable_get(struct hashTable_t *,char *)" (?hashTable_get@@YAPAXPAUhashTable_t@@PAD@Z)  C:\Users\_**_\Documents\**__\TR\Game-Server-experimental\communicator.obj   TabulaGameServer
Error   65  error LNK2019: unresolved external symbol "struct _dynObject_t \* __cdecl controlpoint_create(struct _mapChannel_t *,float,float,float,float)" (?controlpoint_create@@YAPAU_dynObject_t@@PAU_mapChannel_t@@MMMM@Z) referenced in function "bool __cdecl communicator_parseCommand(struct _mapChannelClient_t *,char *)" (?communicator_parseCommand@@YA_NPAU_mapChannelClient_t@@PAD@Z)  C:\Users\_**_\Documents\**__\TR\Game-Server-experimental\communicator.obj   TabulaGameServer
Error   66  error LNK2019: unresolved external symbol "void __cdecl hashTable_init(struct hashTableSynced_t *,int)" (?hashTable_init@@YAXPAUhashTableSynced_t@@H@Z) referenced in function "void __cdecl creature_init(void)" (?creature_init@@YAXXZ)   C:\Users\_**_\Documents\**__\TR\Game-Server-experimental\creature.obj   TabulaGameServer
Error   67  error LNK2019: unresolved external symbol "bool __cdecl hashTable_set(struct hashTableSynced_t *,unsigned int,void *)" (?hashTable_set@@YA_NPAUhashTableSynced_t@@IPAX@Z) referenced in function "void __cdecl _creature_dbCreatureMissile_cb(void *,struct diJob_creatureAction_t *)" (?_creature_dbCreatureMissile_cb@@YAXPAXPAUdiJob_creatureAction_t@@@Z)   C:\Users\_**_\Documents\**__\TR\Game-Server-experimental\creature.obj   TabulaGameServer
Error   68  error LNK2019: unresolved external symbol "void \* __cdecl hashTable_get(struct hashTableSynced_t *,unsigned int)" (?hashTable_get@@YAPAXPAUhashTableSynced_t@@I@Z) referenced in function "void __cdecl _creature_dbCreatureType_cb(void *,struct diJob_creatureType_t *)" (?_creature_dbCreatureType_cb@@YAXPAXPAUdiJob_creatureType_t@@@Z)    C:\Users\_**_\Documents\**__\TR\Game-Server-experimental\creature.obj   TabulaGameServer
Error   69  error LNK2019: unresolved external symbol "void __cdecl DataInterface_Creature_getCreatureTypeList(void (__cdecl_)(void _,struct diJob_creatureType_t *),void *)" (?DataInterface_Creature_getCreatureTypeList@@YAXP6AXPAXPAUdiJob_creatureType_t@@@Z0@Z) referenced in function "void __cdecl creature_init(void)" (?creature_init@@YAXXZ) C:\Users\_**_\Documents\**__\TR\Game-Server-experimental\creature.obj   TabulaGameServer
Error   70  error LNK2019: unresolved external symbol "void __cdecl DataInterface_Creature_getCreatureActionList(void (__cdecl_)(void _,struct diJob_creatureAction_t *),void *)" (?DataInterface_Creature_getCreatureActionList@@YAXP6AXPAXPAUdiJob_creatureAction_t@@@Z0@Z) referenced in function "void __cdecl creature_init(void)" (?creature_init@@YAXXZ) C:\Users\_**_\Documents\**__\TR\Game-Server-experimental\creature.obj   TabulaGameServer
Error   71  error LNK2019: unresolved external symbol "void __cdecl DataInterface_SpawnSystem_getSpawnPoolList(void (__cdecl_)(void _,struct diJob_spawnpool_t *),void *)" (?DataInterface_SpawnSystem_getSpawnPoolList@@YAXP6AXPAXPAUdiJob_spawnpool_t@@@Z0@Z) referenced in function "void __cdecl spawnPool_initForMapChannel(struct _mapChannel_t *)" (?spawnPool_initForMapChannel@@YAXPAU_mapChannel_t@@@Z)   C:\Users\_**_\Documents\**__\TR\Game-Server-experimental\spawnSystem.obj    TabulaGameServer
Error   72  error LNK2019: unresolved external symbol "void __cdecl banedropship_create(struct _mapChannel_t *,float,float,float,int,struct _creatureType_t \* *,struct _spawnPool_t *)" (?banedropship_create@@YAXPAU_mapChannel_t@@MMMHPAPAU_creatureType_t@@PAU_spawnPool_t@@@Z) referenced in function "bool __cdecl _spawnPool_callback(struct _mapChannel_t *,void *,int)" (?_spawnPool_callback@@YA_NPAU_mapChannel_t@@PAXH@Z)    C:\Users\_**_\Documents\**__\TR\Game-Server-experimental\spawnSystem.obj    TabulaGameServer
Error   73  error LNK2019: unresolved external symbol "int __cdecl navmesh_getPath(struct _mapChannel_t *,float \* const,float \* const,float *,bool)" (?navmesh_getPath@@YAHPAU_mapChannel_t@@QAM1PAM_N@Z) referenced in function "void __cdecl controller_creatureThink(struct _mapChannel_t *,struct _creature_t *,int,bool *)" (?controller_creatureThink@@YAXPAU_mapChannel_t@@PAU_creature_t@@HPA_N@Z)  C:\Users\_**_\Documents\**__\TR\Game-Server-experimental\behaviorController.obj TabulaGameServer
Error   74  error LNK2019: unresolved external symbol "public: __thiscall INIParser::INIParser(char const *)" (??0INIParser@@QAE@PBD@Z) referenced in function "void __cdecl DataInterface_init(void)" (?DataInterface_init@@YAXXZ) C:\Users\_**_\Documents\**__\TR\Game-Server-experimental\DataInterface.obj  TabulaGameServer
Error   75  error LNK2019: unresolved external symbol "public: __thiscall INIParser::~INIParser(void)" (??1INIParser@@QAE@XZ) referenced in function "public: void \* __thiscall INIParser::`scalar deleting destructor'(unsigned int)" (??_GINIParser@@QAEPAXI@Z)   C:\Users\_**_\Documents\**__\TR\Game-Server-experimental\DataInterface.obj  TabulaGameServer
Error   76  error LNK2019: unresolved external symbol "public: int __thiscall INIParser::GetInt(char const *,char const *,int)" (?GetInt@INIParser@@QAEHPBD0H@Z) referenced in function "void __cdecl DataInterface_init(void)" (?DataInterface_init@@YAXXZ)    C:\Users\_**_\Documents\**__\TR\Game-Server-experimental\DataInterface.obj  TabulaGameServer
Error   77  error LNK2019: unresolved external symbol "public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __thiscall INIParser::GetString(char const *,char const *,char const *)" (?GetString@INIParser@@QAE?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PBD00@Z) referenced in function "void __cdecl DataInterface_init(void)" (?DataInterface_init@@YAXXZ)  C:\Users\_**_\Documents\**__\TR\Game-Server-experimental\DataInterface.obj  TabulaGameServer
Error   78  error LNK1120: 25 unresolved externals  C:\Users\_**_\Documents\**_*\TR\Game-Server-experimental\Debug\TabulaGameServer.exe TabulaGameServer

**Comment by kthxbye** [comment]
All the "unresolved external symbol" messages of methods defined in our source are a sign that the compiler does not find the .cpp files, but the header files are linked correctly. This could also be caused by a missing lib file. I just noticed that besides libmysql.lib there is also a "pthreadVC2.lib" inside 3rdparty/pthreads/ - Maybe it works if you copy that one to the main directory too.

Edit: Also, if there are any .cpp files flagged as "excluded" try to remove & re-add them to the project. From what I have seen, all .cpp files are in the main directory.
